version: "3.9"

services:
  whoami:
    image: traefik/whoami
    networks:
      # `default` must be specified if you need to communicate with other
      # services defined in this compose file.
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.routers.whoami.entrypoints=web

networks:
  traefik:
    name: traefik
    external: true
