version: "3.9"

services:
  traefik:
    restart: unless-stopped
    labels:
      # Middleware:
      # dashboard-auth@file - HTTP basic auth
      # redirect-https@file - Redirect to HTTPS
      # enforce-hsts@file - Enable HSTS to make browsers force HTTPS for one year
      # enforce-hsts-permanent@file - Replace `enforce-hsts@file` with this to preload HSTS. See https://hstspreload.org/
      - traefik.http.routers.traefik-dashboard.middlewares=redirect-https@file,dashboard-auth@file,enforce-hsts@file
      - traefik.http.routers.traefik-api.middlewares=redirect-https@file,dashboard-auth@file,enforce-hsts@file

      # Specify domain used to access Traefik dashboard in production
      # - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.example.com`)
      # - traefik.http.routers.traefik-api.rule=Host(`traefik.example.com`) && PathPrefix(`/api`)

      # Use Let's Encrypt to generate certificates
      # Configure using config/traefik.yml
      # - traefik.http.routers.whoami.tls.certResolver=lets-encrypt

      # Optional: Manually define domains to include in certificate (defaults to using routing rules)
      # - traefik.http.routers.whoami.tls.domains[0].main=traefik.example.com
      # - traefik.http.routers.whoami.tls.domains[0].sans[0]=*.example.com
