version: "3.9"

services:
  traefik:
    restart: unless-stopped
    labels:
      # Middleware:
      # dashboard-auth@file - HTTP basic auth
      # redirect-https@file - Redirect to HTTPS
      # enforce-hsts@file - Enable HSTS to make browsers force HTTPS for one year
      # enforce-hsts-permanent@file - Replace `enforce-hsts@file` with this to preload HSTS. See https://hstspreload.org/
      - traefik.http.routers.traefik-dashboard.middlewares=redirect-https@file,dashboard-auth@file,enforce-hsts@file
      - traefik.http.routers.traefik-api.middlewares=redirect-https@file,dashboard-auth@file,enforce-hsts@file
