version: "3.9"

services:
  whoami:
    image: traefik/whoami
    networks:
      # `default` must be specified if you need to communicate with other
      # services defined in this compose file.
      - default
      - traefik
    labels:
      # Enable Traefik on this container
      - traefik.enable=true

      # Specify hostname and other routing rules
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)

      # Middleware:
      # redirect-https@file - Redirect to HTTPS
      # enforce-hsts@file - Enable HSTS to make browsers force HTTPS for one year
      # enforce-hsts-permanent@file - Replace `enforce-hsts@file` with this to preload HSTS. See https://hstspreload.org/
      - traefik.http.routers.whoami.middlewares=redirect-https@file,enforce-hsts@file

      # Use Let's Encrypt to generate certificates
      # Configure using config/traefik.yml
      # - traefik.http.routers.whoami.tls.certResolver=lets-encrypt

      # Optional: Manually define domains to include in certificate (defaults to using routing rules)
      # - traefik.http.routers.whoami.tls.domains[0].main=whoami.example.com
      # - traefik.http.routers.whoami.tls.domains[0].sans[0]=*.example.com

networks:
  traefik:
    name: traefik
    external: true
