version: "3.9"

services:
  whoami:
    image: traefik/whoami
    networks:
      # `default` must be specified if you need to communicate with other
      # services defined in this compose file.
      - default
      - traefik
    labels:
      # Enable Traefik on this container
      - traefik.enable=true

      # Specify hostname and other routing rules
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)


networks:
  traefik:
    name: traefik
    external: true
