version: "3.9"

services:
  traefik:
    labels:
      - traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth@file
      - traefik.http.routers.traefik-api.middlewares=dashboard-auth@file
