# log:
#   level: DEBUG

api: true

providers:
  docker:
    network: traefik
    exposedbydefault: false
    defaultRule: Host(`{{normalize .Name}}.localhost`)
  file:
    directory: /etc/traefik/dynamic_config/
    watch: true

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls: true

certificatesResolvers:
  lets-encrypt:
    acme:
      # email: "your_email_address_here@yourdomain.com"

      storage: /data/acme.json

      # Remove below line after you have everything working
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Let's Encrypt Staging

      # TLS-ALPN-01 challenge. Should "just work" if Traefik is publicly exposed.
      # Otherwise see https://doc.traefik.io/traefik/https/acme/#dnschallenge
      tlsChallenge: {}
