# log:
#   level: DEBUG

api: true

providers:
  docker:
    exposedbydefault: false
    defaultRule: Host(`{{normalize .Name}}.localhost`)
  file:
    directory: /etc/traefik/dynamic_config/
    watch: true

entrypoints:
  web:
    address: ":80"
